"""Build the site's CSS with the Tailwind standalone CLI.

    .venv/Scripts/python -m vyuha_platform css            # one build, minified
    .venv/Scripts/python -m vyuha_platform css --watch    # rebuild as templates change

The CLI comes from ``tools/fetch_assets.py``: the standalone binary in ``tools/bin/`` when
GitHub is reachable, otherwise the npm build in ``tools/tailwind/`` run with Node. The
compiled ``static/app/app.css`` is committed, so running the app never needs this — only
changing the templates or the design tokens does.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BIN = ROOT / "tools" / "bin" / ("tailwindcss.exe" if sys.platform == "win32" else "tailwindcss")
NPM_CLI = ROOT / "tools" / "tailwind" / "node_modules" / "@tailwindcss" / "cli"
SRC = Path(__file__).resolve().parent / "assets" / "app.css"
OUT = ROOT / "vyuha_platform" / "static" / "app" / "app.css"


def _cli() -> list[str] | None:
    """How to run Tailwind here: the standalone binary, or its npm build under Node."""
    if BIN.exists():
        return [str(BIN)]
    manifest = NPM_CLI / "package.json"
    node = shutil.which("node")
    if manifest.exists() and node:
        entry = json.loads(manifest.read_text(encoding="utf-8")).get("bin")
        if isinstance(entry, dict):
            entry = entry.get("tailwindcss") or next(iter(entry.values()), "")
        if entry:
            return [node, str((NPM_CLI / entry).resolve())]
    return None


#: Where the source is written out for the npm build (see ``_entry``).
ENTRY = ROOT / "tools" / "tailwind" / "entry.css"


def _entry(cli: list[str]) -> Path:
    """The file to hand the CLI.

    The standalone binary carries Tailwind inside it and reads the source where it is.
    The npm build resolves ``@import "tailwindcss"`` from the importing file's own folder,
    and the package lives in ``tools/tailwind/node_modules`` — so for that build the
    source is written out beside it, with its two relative paths re-pointed.
    """
    if cli[0] == str(BIN):
        return SRC

    def rel(path: Path) -> str:
        return os.path.relpath(path, ENTRY.parent).replace(os.sep, "/")

    text = SRC.read_text(encoding="utf-8")
    text = text.replace('"../../static/app/fonts/fonts.css"',
                        f'"{rel(ROOT / "vyuha_platform" / "static" / "app" / "fonts" / "fonts.css")}"')
    text = text.replace('@source "../templates";',
                        f'@source "{rel(SRC.parent.parent / "templates")}";')
    ENTRY.write_text("/* Generated by vyuha_platform/web/build.py from web/assets/app.css"
                     " — edit that file, not this one. */\n" + text, encoding="utf-8")
    return ENTRY


def build_css(watch: bool = False, minify: bool = True) -> int:
    cli = _cli()
    if cli is None:
        print("The Tailwind CLI is missing. Fetch it with:\n"
              "  .venv/Scripts/python tools/fetch_assets.py")
        return 1
    cmd = [*cli, "-i", str(_entry(cli)), "-o", str(OUT)]
    if minify:
        cmd.append("--minify")
    if watch:
        cmd.append("--watch")
    return subprocess.call(cmd, cwd=str(SRC.parent))
