"""Fetch the site's third-party front-end assets, pinned.

    .venv/Scripts/python tools/fetch_assets.py            # use the pins in assets.lock.json
    .venv/Scripts/python tools/fetch_assets.py --latest   # resolve newer versions, rewrite pins

Everything the browser loads is served from ``/static/app`` — no CDN at runtime — because the
site has to keep working on a slow shop connection and must not change underneath us when a CDN
does. The Tailwind CLI is a build tool, not a runtime asset: it lands in ``tools/bin/``
(gitignored) and is verified against the release's own ``sha256sums.txt``.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import stat
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATIC = ROOT / "vyuha_platform" / "static" / "app"
BIN = ROOT / "tools" / "bin"
LOCK = ROOT / "tools" / "assets.lock.json"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36")

DEFAULT_PINS = {"htmx": "2.0.4", "alpine": "3.14.9", "lucide": "", "tailwind": ""}

FONTS_URL = ("https://fonts.googleapis.com/css2?family=Archivo:wght@600;700;800"
             "&family=Schibsted+Grotesk:wght@400;500;600;700"
             "&family=JetBrains+Mono:wght@400;500;600&display=swap")
FONT_SUBSETS = ("latin", "latin-ext")          # latin-ext carries the ₹ sign

#: Lucide icon names (lucide.dev). Missing names are reported, not fatal.
ICONS = [
    "house", "trending-up", "package", "wallet", "users", "chart-column", "inbox",
    "database", "settings", "search", "plus", "bell", "sparkles", "menu", "x",
    "chevron-right", "chevron-down", "chevron-left", "check", "circle-check", "circle",
    "circle-dot", "triangle-alert", "circle-alert", "info", "arrow-up-right",
    "arrow-down-right", "clock", "sun", "moon", "log-out", "building-2", "store",
    "file-text", "upload", "camera", "keyboard", "list-checks", "map", "rocket", "layers",
    "calendar", "phone", "mail", "message-circle", "external-link", "refresh-cw", "ellipsis",
    "user-plus", "package-plus", "receipt", "credit-card", "landmark", "truck",
    "clipboard-list", "command", "arrow-left", "arrow-right", "lock", "trash-2", "pencil",
    "filter", "eye", "sliders-horizontal", "indian-rupee", "boxes", "shopping-cart",
    "file-spreadsheet", "scan-line", "hand-coins", "badge-check", "sprout", "wrench",
    "factory", "pill", "shirt", "milk", "wheat", "shopping-basket", "warehouse",
    "git-branch", "history", "notebook-pen", "square-pen", "circle-help", "panel-left",
    "zap", "target", "percent", "calendar-check", "user-round", "file-check", "send",
]

TAILWIND_ASSET = {
    "win32": "tailwindcss-windows-x64.exe",
    "linux": "tailwindcss-linux-x64",
    "darwin": "tailwindcss-macos-arm64",
}


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def load_pins(latest: bool) -> dict:
    pins = dict(DEFAULT_PINS)
    if LOCK.exists() and not latest:
        pins.update(json.loads(LOCK.read_text(encoding="utf-8")))
    return pins


def fetch_vendor(pins: dict) -> None:
    out = STATIC / "vendor"
    out.mkdir(parents=True, exist_ok=True)
    files = {
        "htmx.min.js": f"https://cdn.jsdelivr.net/npm/htmx.org@{pins['htmx']}/dist/htmx.min.js",
        "alpine.min.js": f"https://cdn.jsdelivr.net/npm/alpinejs@{pins['alpine']}/dist/cdn.min.js",
        "alpine-focus.min.js":
            f"https://cdn.jsdelivr.net/npm/@alpinejs/focus@{pins['alpine']}/dist/cdn.min.js",
    }
    for name, url in files.items():
        data = get(url)
        (out / name).write_bytes(data)
        print(f"  vendor  {name:22} {len(data) // 1024:>4} KB")


def fetch_fonts() -> None:
    out = STATIC / "fonts"
    out.mkdir(parents=True, exist_ok=True)
    css = get(FONTS_URL).decode()
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
    saved: dict[str, str] = {}
    faces = []
    for subset, block in blocks:
        if subset not in FONT_SUBSETS:
            continue
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([\d ]+);", block).group(1).strip()
        if url not in saved:
            name = f"{family.replace(' ', '')}-{weight.replace(' ', '_')}-{subset}.woff2"
            (out / name).write_bytes(get(url))
            saved[url] = name
        faces.append(block.replace(url, f"/static/app/fonts/{saved[url]}"))
    (out / "fonts.css").write_text(
        "/* Generated by tools/fetch_assets.py — do not edit. */\n" + "\n".join(faces) + "\n",
        encoding="utf-8")
    print(f"  fonts   {len(saved)} files, {len(faces)} faces")


def fetch_icons(pins: dict) -> None:
    version = pins.get("lucide") or json.loads(
        get("https://cdn.jsdelivr.net/npm/lucide-static/package.json"))["version"]
    pins["lucide"] = version
    symbols, missing = [], []
    for name in ICONS:
        try:
            svg = get(f"https://cdn.jsdelivr.net/npm/lucide-static@{version}/icons/{name}.svg").decode()
        except Exception:                                       # noqa: BLE001
            missing.append(name)
            continue
        inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1).strip()
        inner = re.sub(r"\s+", " ", inner)
        symbols.append(f'<symbol id="i-{name}" viewBox="0 0 24 24">{inner}</symbol>')
    sprite = ('<svg xmlns="http://www.w3.org/2000/svg">'
              f"<!-- Lucide {version} (ISC), generated by tools/fetch_assets.py -->"
              + "".join(symbols) + "</svg>\n")
    (STATIC / "icons.svg").write_text(sprite, encoding="utf-8")
    print(f"  icons   lucide {version}: {len(symbols)} icons"
          + (f", missing: {', '.join(missing)}" if missing else ""))


NPM_DIR = ROOT / "tools" / "tailwind"


def fetch_tailwind(pins: dict) -> None:
    """The standalone binary from GitHub; the npm build (run with Node) if GitHub is out
    of reach — some networks block it while the npm registry answers fine."""
    try:
        _tailwind_from_github(pins)
    except Exception as exc:                                    # noqa: BLE001
        print(f"  tailwind: GitHub unreachable ({type(exc).__name__}) — using npm instead")
        _tailwind_from_npm(pins)


def _tailwind_from_npm(pins: dict) -> None:
    npm = shutil.which("npm")
    if not npm:
        raise SystemExit("Tailwind needs either GitHub access or Node.js with npm installed.")
    version = pins.get("tailwind_npm") or "4"
    subprocess.check_call(
        [npm, "install", "--prefix", str(NPM_DIR), f"@tailwindcss/cli@{version}",
         f"tailwindcss@{version}", "--no-audit", "--no-fund", "--loglevel", "error"],
        shell=(sys.platform == "win32"))
    manifest = NPM_DIR / "node_modules" / "@tailwindcss" / "cli" / "package.json"
    pins["tailwind_npm"] = json.loads(manifest.read_text(encoding="utf-8"))["version"]
    print(f"  tailwind npm @tailwindcss/cli {pins['tailwind_npm']} -> tools/tailwind/")


def _tailwind_from_github(pins: dict) -> None:
    asset_name = TAILWIND_ASSET.get(sys.platform)
    if not asset_name:
        print(f"  tailwind: no standalone build for {sys.platform}; skipped")
        return
    tag = pins.get("tailwind")
    api = ("https://api.github.com/repos/tailwindlabs/tailwindcss/releases/"
           + (f"tags/{tag}" if tag else "latest"))
    release = json.loads(get(api))
    tag = release["tag_name"]
    pins["tailwind"] = tag
    assets = {a["name"]: a["browser_download_url"] for a in release["assets"]}
    binary = get(assets[asset_name])
    sums = get(assets["sha256sums.txt"]).decode()
    expected = next((ln.split()[0] for ln in sums.splitlines()
                     if ln.strip().endswith(asset_name)), "")
    actual = hashlib.sha256(binary).hexdigest()
    if expected and expected != actual:
        raise SystemExit(f"tailwind checksum mismatch: expected {expected}, got {actual}")
    BIN.mkdir(parents=True, exist_ok=True)
    target = BIN / ("tailwindcss.exe" if sys.platform == "win32" else "tailwindcss")
    target.write_bytes(binary)
    if sys.platform != "win32":
        target.chmod(target.stat().st_mode | stat.S_IEXEC)
    print(f"  tailwind {tag} -> {target.relative_to(ROOT)} "
          f"({len(binary) // 1_048_576} MB, sha256 {'verified' if expected else 'not published'})")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--latest", action="store_true", help="resolve newer versions and re-pin")
    ap.add_argument("--no-tailwind", action="store_true", help="skip the build tool download")
    args = ap.parse_args()

    pins = load_pins(args.latest)
    print("Fetching front-end assets")
    fetch_vendor(pins)
    fetch_fonts()
    fetch_icons(pins)
    # Pinned before the build tool, so a failure there never loses the runtime pins.
    LOCK.write_text(json.dumps(pins, indent=2) + "\n", encoding="utf-8")
    if not args.no_tailwind:
        fetch_tailwind(pins)
    LOCK.write_text(json.dumps(pins, indent=2) + "\n", encoding="utf-8")
    print(f"  pins    {LOCK.relative_to(ROOT)}: {pins}")


if __name__ == "__main__":
    main()
